---
- name: "INSTANCE SPECIFIC SETUP"
  hosts: jenkins-instance
  become: yes

  roles:

    - { role: "os/group"
       ,name: "jenkins"
      }

    - { role: "os/user"
       ,name: "jenkins"
       ,group: "jenkins"
       ,comment: "System user for jenkins installation"
       ,state: "present"
       ,system: True
       }

  post_tasks:

    - file:
        dest: "{{install_prefix}}/jenkins/{{jenkins_instance_name}}"
        owner: "jenkins"
        mode: "0700"
        state: "directory"

- name: "INSTANCE SPECIFIC SETUP"
  hosts: jenkins-instance
  become: yes
  become_user: jenkins

  roles:

    # This will create a tomcat instance at CATALINA_BASE
    - { role: "apache/tomcat-8/instance",
        #catalina_base: "{{catalina_base}}",
        #catalina_home: "{{catalina_home}}",
        # The rest is optional
        server_port: 9009,
        http_connector_port: 8000,
        ajp_connector_port: 8001,
        manager_apps: []
      }

    # deploy jenkins to JENKINS_HOME
    - { role: "jenkins/deploy",
        catalina_base: "{{catalina_base}}",
        version: "{{jenkins_version}}",
        checksum: "{{jenkins_checksum}}",
        context_path: "ROOT"
      }

    # install, disable jenkins plugins in JENKINS_HOME
    - { role: "jenkins/plugins",
        plugins: "{{jenkins_plugins}}"
      }

    # Now the configuration begins.
    #
    - { role: "jenkins/configure",
        #admin_email: "info@michael-jansen.biz",
        number_of_executors: "4",
        node_mode: "normal",
        node_labels: "my super lablels",
        authentication_strategy: "hudson_private",
        authorization_strategy: "project_matrix",
        users: [
          {
          id: 'admin',
          password: 'admin',
          fullname: "Technical Administration Account",
          email: 'admin@example.com',
          permissions: [ "hudson.model.Hudson.Administer" ]
          },
          {
          id: 'mjansen',
          password: 'mjansen',
          email: 'mjansen@example.com',
          fullname: "Michael Jansen",
          permissions: [ "hudson.model.Hudson.Administer" ]
          },
          {
          id: 'test1',
          password: 'mjansen',
          email: 'mjansen@example.com',
          fullname: "Michael Jansen",
          permissions: [
            "hudson.model.Computer.Configure",
            "hudson.model.Item.Discover",
            "hudson.model.View.Delete",
            "hudson.model.Run.Update",
            "com.cloudbees.plugins.credentials.CredentialsProvider.Update" ]
          }
        ]
      }

    - { role: "jenkins/configure-email-notification",
        smtp_replyto: "mike@michael-jansen.name",
        smtp_host: "smtp.1und1.de",
        smtp_username: "info@michael-jansen.biz",
        smtp_password: "<enter password here>"
      }

    - { role: "jenkins/configure-proxy",
        # proxy_host: "localhost",
        # proxy_port: "8080",
        # proxy_no_proxy: "*.default\nlocalhost",
        # proxy_username: "mjansen",
        # proxy_password: "dhdhdhdh"
      }

    - { role: "jenkins/bootstrap-job",
        git_repo: 'http://192.168.122.1/bootstrap'
      }
