---
- name: Requirements for jenkins deployment
  sudo: true
  hosts: jenkins
  gather_facts: No

  roles:

    - { role: "os/group"
       ,name: "jenkins"
      }

    - { role: "os/user"
       ,name: "jenkins"
       ,group: "jenkins"
       ,comment: "System user for jenkins installation"
       ,state: "present"
       ,system: True
       }

  tasks:

    - name: Create prefix for java
      file:
      args:
        path: "/opt/java"
        state: "directory"
        mode: "0755"
        owner: "root"
        group: "root"

    - name: Create prefix for tomcat
      file:
      args:
        path: "/opt/apache/tomcat"
        state: "directory"
        mode: "0700"
        owner: "jenkins"
        group: "jenkins"

    - name: Create prefix for jenkins
      file:
      args:
        path: "/opt/jenkins"
        state: "directory"
        mode: "0700"
        owner: "jenkins"
        group: "jenkins"


- name: Execute java install
  sudo: true
  hosts: jenkins
  gather_facts: No

  vars:

  roles:

    - { role: "lang/java/oracle",
      }

- name: Execute jenkins install
  sudo: true
  sudo_user: "jenkins"
  hosts: jenkins
  gather_facts: No

  vars:
    - java_home: "/opt/java/jdk1.8.0_65"
    - tomcat_version: 8.0.29
    - jenkins_version: 1.585

    - jenkins_plugins:

      # CVS Plug-in
      - name: cvs
        version: "2.12"
        enabled: false
        bundled: true
        pinned: yes

      # Javadoc Plugin
      - name: javadoc
        version: "1.3"
        enabled: true
        bundled: true
        pinned: yes

      # SSH Credentials Plugin
      - name: ssh-credentials
        version: "1.11"
        enabled: true
        bundled: true
        pinned: yes

      # Mailer Plugin
      - name: mailer
        version: "1.16"
        enabled: true
        bundled: true
        pinned: yes

      # Credentials Plugin
      - name: credentials
        version: "1.24"
        enabled: true
        bundled: true
        pinned: true

      # External Monitor Job Type Plugin
      - name: external-monitor-job
        version: "1.4"
        enabled: true
        bundled: true
        pinned: yes

      # SSH Slaves plugin
      - name: ssh-slaves
        version: "1.10"
        enabled: true
        bundled: true
        pinned: yes

      # Ant Plugin
      - name: ant
        version: "1.2"
        enabled: true
        bundled: true
        pinned: false

      # Subversion Plug-in
      - name: subversion
        version: "2.5.5"
        enabled: true
        bundled: true
        pinned: yes

      # PAM Authentication plugin
      - name: pam-auth
        version: "1.2"
        enabled: false
        bundled: true
        pinned: yes

      # Translation Assistance plugin
      - name: translation
        version: "1.12"
        enabled: false
        bundled: true
        pinned: yes

      # Maven Integration plugin
      - name: maven-plugin
        version: "2.12.1"
        enabled: false
        bundled: true
        pinned: yes

      # Matrix Project Plugin
      - name: matrix-project
        version: "1.4"
        enabled: true
        bundled: true
        pinned: yes

      # OWASP Markup Formatter Plugin
      - name: antisamy-markup-formatter
        version: "1.3"
        enabled: true
        bundled: true
        pinned: yes

      # JUnit Plugin
      - name: junit
        version: "1.10"
        enabled: true
        bundled: true
        pinned: yes

      # LDAP Plugin
      - name: ldap
        version: "1.11"
        enabled: false
        bundled: true
        pinned: yes

      # Role-based Authorization Strategy
      - name: role-strategy
        version: "2.2.0"
        enabled: true
        bundled: false
        pinned: false

      # Matrix Authorization Strategy Plugin
      - name: matrix-auth
        version: "1.2"
        enabled: true
        bundled: true
        pinned: yes

      # Windows Slaves Plugin
      - name: windows-slaves
        version: "1.1"
        enabled: false
        bundled: true
        pinned: yes

    - tomcat_home: "/opt/jenkins/tomcat"

  pre_tasks:
    - name: STOP TOMCAT
      # =====================================================================
      command: "nohup {{tomcat_home}}/bin/catalina.sh stop 2>&1"
      ignore_errors: true

  roles:

    # This will download and install tomcat on the remote server to apache_tomcat_prefix
    - { role: "apache/tomcat-8",
        tomcat_version: "{{tomcat_version}}",
        tomcat_checksum: "4b7ba7a5af0a5c395c0740fc011b59d1"
      }

    # This will create a tomcat instance at CATALINA_BASE
    - { role: "apache/tomcat-8-instance",
        catalina_base: "/opt/jenkins/tomcat",
        catalina_home: "/opt/apache/tomcat/apache-tomcat-{{tomcat_version}}",
        # The rest is optional
        server_port: 9009,
        http_connector_port: 8000,
        ajp_connector_port: 8001
      }

    # deploy jenkins to JENKINS_HOME
    - { role: "jenkins/core",
        tomcat_home: "/opt/jenkins/tomcat",
        jenkins_home: "~/.jenkins"
      }

    # install, disable jenkins plugins in JENKINS_HOME
    - { role: "jenkins/plugins",
        jenkins_home: "~/.jenkins"
      }

    # Now the configuration begins.
    # Permissions:
    #  Computer.:: Slave  (hudson.model.Computer)
    #  CredentialsProvider:: Permissions  (com.cloudbees.plugins.credentials.CredentialsProvider)
    #  Hudson:: Overall   (hudson.model.Hudson)
    #  Item:: Job         (hudson.model.Item)
    #  Run:: Run          (hudson.model.Run)
    #  View:: View        (hudson.model.View)
    #
    - { role: "jenkins/configuration",
        jenkins_home: "~/.jenkins",
        authentication_strategy: "hudson_private",
        authorization_strategy: "project_matrix",
        users: [
          {
          id: 'admin',
          password: 'admin',
          fullname: "Technical Administration Account",
          email: 'admin@example.com',
          permissions: [ "hudson.model.Hudson.Administer" ]
          },
          {
          id: 'mjansen',
          password: 'mjansen',
          email: 'mjansen@example.com',
          fullname: "Michael Jansen",
          permissions: [ "hudson.model.Hudson.Administer" ]
          },
          {
          id: 'test1',
          password: 'mjansen',
          email: 'mjansen@example.com',
          fullname: "Michael Jansen",
          permissions: [ "hudson.model.Computer.Configure", "hudson.model.Item.Discover", "hudson.model.View.Delete",
           "hudson.model.Run.Update", "com.cloudbees.plugins.credentials.CredentialsProvider.Update" ]
          }
        ]
      }

  post_tasks:
    - name: START TOMCAT
      # =====================================================================
      command: "nohup {{tomcat_home}}/bin/catalina.sh start 2>&1"
