---
- name: Requirements for jenkins deployment
  sudo: true
  hosts: jenkins
  gather_facts: No

  pre_tasks:

    - name: Install git
      action: zypper
      args:
        name: git
        state: present

  post_tasks:

    - name: Create prefix for java
      file:
      args:
        path: "/{{install_prefix}}/java"
        state: "directory"
        mode: "0755"

    - name: Create prefix for tomcat
      file:
      args:
        path: "/{{install_prefix}}/apache-tomcat"
        state: "directory"
        mode: "0755"

    - name: Create prefix for jenkins
      file:
      args:
        path: "/{{install_prefix}}/jenkins"
        state: "directory"
        mode: "0755"
        owner: "jenkins"
        group: "jenkins"

    - name: Create prefix for groovy
      file:
      args:
        path: "/{{install_prefix}}/groovy-sdk"
        state: "directory"
        mode: "0755"

    - name: Create prefix for jenkins_home
      file:
      args:
        path: "/var/jenkins"
        state: "directory"
        mode: "0755"
        owner: "jenkins"
        group: "jenkins"


  roles:

    - { role: "os/group"
       ,name: "jenkins"
      }

    - { role: "os/user"
       ,name: "jenkins"
       ,group: "jenkins"
       ,comment: "System user for jenkins installation"
       ,state: "present"
       ,system: True
       }

- name: Requirements for jenkins deployment
  sudo: true
  hosts: jenkins
  gather_facts: No

  vars:

    - tomcat_version: 8.0.29
    - tomcat_checksum: "4b7ba7a5af0a5c395c0740fc011b59d1"

  roles:

    - { role: "lang/java/oracle-sdk",
        platform: "linux-x64",
        version: "1.8.0_65",
        format: "tar.gz",
        build: "17"
      }

    - { role: "lang/java/oracle-sdk",
        platform: "linux-x64",
        version: "1.8.0_73",
        format: "tar.gz",
        build: "02"
      }

    - { role: "lang/groovy",
        version: "2.4.5"
      }

    # This will download and install tomcat on the remote server to apache_tomcat_prefix
    - { role: "apache/tomcat-8/install",
        version: "{{tomcat_version}}",
        checksum: "{{tomcat_checksum}}"
      }



- name: Execute jenkins install
  sudo: true
  sudo_user: "jenkins"
  hosts: jenkins
  gather_facts: No

  vars:
    - java_home: "/{{install_prefix}}/java/jdk1.8.0_65"
    - tomcat_version: 8.0.29
    - tomcat_checksum: "4b7ba7a5af0a5c395c0740fc011b59d1"
    - catalina_base: "/{{install_prefix}}/jenkins/tomcat"
    - jenkins_version: 1.643
    - jenkins_home: "/var/jenkins"
    - jenkins_plugins:

      # CVS Plug-in
      - name: cvs
        version: "2.12"
        enabled: true
        bundled: true
        pinned: yes

      # Javadoc Plugin
      - name: javadoc
        version: "1.3"
        enabled: true
        bundled: true
        pinned: yes

      # SSH Credentials Plugin
      - name: ssh-credentials
        version: "1.11"
        enabled: true
        bundled: true
        pinned: yes

      # Mailer Plugin
      - name: mailer
        version: "1.16"
        enabled: true
        bundled: true
        pinned: yes

      # Credentials Plugin
      - name: credentials
        version: "1.24"
        enabled: true
        bundled: true
        pinned: yes

      # Script Security Plugin
      - name: script-security
        version: "1.15"
        enabled: true
        bundled: true
        pinned: yes

      # External Monitor Job Type Plugin
      - name: external-monitor-job
        version: "1.4"
        enabled: true
        bundled: true
        pinned: false

      # SSH Slaves plugin
      - name: ssh-slaves
        version: "1.10"
        enabled: true
        bundled: true
        pinned: yes

      # Ant Plugin
      - name: ant
        version: "1.2"
        enabled: true
        bundled: true
        pinned: false

      # Subversion Plug-in
      - name: subversion
        version: "2.5.5"
        enabled: false
        bundled: true
        pinned: yes

      # PAM Authentication plugin
      - name: pam-auth
        version: "1.2"
        enabled: true
        bundled: true
        pinned: yes

      # Translation Assistance plugin
      - name: translation
        version: "1.12"
        enabled: true
        bundled: true
        pinned: yes

      # Maven Integration plugin
      - name: maven-plugin
        version: "2.12.1"
        enabled: true
        bundled: true
        pinned: yes

      # Matrix Project Plugin
      - name: matrix-project
        version: "1.6"
        enabled: true
        bundled: true
        pinned: yes

      # OWASP Markup Formatter Plugin
      - name: antisamy-markup-formatter
        version: "1.3"
        enabled: true
        bundled: true
        pinned: yes

      # JUnit Plugin
      - name: junit
        version: "1.10"
        enabled: true
        bundled: true
        pinned: yes

      # LDAP Plugin
      - name: ldap
        version: "1.11"
        enabled: true
        bundled: true
        pinned: false

      # Matrix Authorization Strategy Plugin
      - name: matrix-auth
        version: "1.2"
        enabled: true
        bundled: true
        pinned: yes

      # Windows Slaves Plugin
      - name: windows-slaves
        version: "1.1"
        enabled: true
        bundled: true
        pinned: yes

      # Job DSL Pluign
      - name: job-dsl
        version: "1.41"
        enabled: true
        bundled: no
        pinned: no

      # SCM API Plugin
      - name: scm-api
        version: "0.2"
        enabled: true
        bundled: no
        pinned: no

      # GIT Client Plugin
      - name: git-client
        version: "1.18.0"
        enabled: true
        bundled: no
        pinned: no

      # Git Plugin
      - name: git
        version: "2.4.0"
        enabled: true
        bundled: no
        pinned: no

  pre_tasks:

    - name: STOP TOMCAT
      # =====================================================================
      command: "nohup {{catalina_base}}/bin/catalina.sh stop 2>&1"
      ignore_errors: true

  roles:

    # This will create a tomcat instance at CATALINA_BASE
    - { role: "apache/tomcat-8/instance",
        catalina_base: "{{catalina_base}}",
        catalina_home: "/{{install_prefix}}/apache-tomcat/apache-tomcat-{{tomcat_version}}",
        # The rest is optional
        server_port: 9009,
        http_connector_port: 8000,
        ajp_connector_port: 8001,
        manager_apps: []
      }

    # deploy jenkins to JENKINS_HOME
    - { role: "jenkins/deploy",
        catalina_base: "{{catalina_base}}",
        version: "{{jenkins_version}}",
        checksum: "{{jenkins_checksum}}",
      }

    # install, disable jenkins plugins in JENKINS_HOME
    - { role: "jenkins/plugins",
        plugins: "{{jenkins_plugins}}"
      }

    # Now the configuration begins.
    #
    - { role: "jenkins/configure",
        #admin_email: "info@michael-jansen.biz",
        number_of_executors: "4",
        node_mode: "normal",
        node_labels: "my super lablels",
        authentication_strategy: "hudson_private",
        authorization_strategy: "project_matrix",
        users: [
          {
          id: 'admin',
          password: 'admin',
          fullname: "Technical Administration Account",
          email: 'admin@example.com',
          permissions: [ "hudson.model.Hudson.Administer" ]
          },
          {
          id: 'mjansen',
          password: 'mjansen',
          email: 'mjansen@example.com',
          fullname: "Michael Jansen",
          permissions: [ "hudson.model.Hudson.Administer" ]
          },
          {
          id: 'test1',
          password: 'mjansen',
          email: 'mjansen@example.com',
          fullname: "Michael Jansen",
          permissions: [
            "hudson.model.Computer.Configure",
            "hudson.model.Item.Discover",
            "hudson.model.View.Delete",
            "hudson.model.Run.Update",
            "com.cloudbees.plugins.credentials.CredentialsProvider.Update" ]
          }
        ]
      }

    - { role: "jenkins/configure-email-notification",
        smtp_replyto: "mike@michael-jansen.name",
        smtp_host: "smtp.1und1.de",
        smtp_username: "info@michael-jansen.biz",
        smtp_password: "<enter password here>"
      }

    - { role: "jenkins/configure-proxy",
        # proxy_host: "localhost",
        # proxy_port: "8080",
        # proxy_no_proxy: "*.default\nlocalhost",
        # proxy_username: "mjansen",
        # proxy_password: "dhdhdhdh"
      }

    - { role: "jenkins/bootstrap-job",
        git_repo: 'http://192.168.122.1/bootstrap'
      }

  post_tasks:

    - name: START TOMCAT
      # =====================================================================
      command: "nohup {{catalina_base}}/bin/catalina.sh start 2>&1"
